### ISSUE TITLE
Tracking API Avalonia Widget support

### ISSUE THREAD

**Issue by edgarfgp** [fabulous-dev/Fabulous.Avalonia#21]
In order to track Avalonia support, we need to make sure we have widgets and modifiers for the following controls

## Base
- [x] Inteactive 
- [x] Layoutable
- [x] Visual
- [x] InputElement
- [x] Control
- [x] StyledElement 
- [x] Panel
- [x] ContentPresenter
- [x] Animatable
- [x] RenderOptions
- [x] ContentControl
- [x] RangeBase
- [X] FlyoutBase
- [x] Transitions
- [x] Animations
- [x] PageTransitions
- [x] Styles

## Primitives

- [x] TemplatedControl
- [x] HeaderedContentControl (We won't support IDataTemplate for now. So no need to wrap those properties)
- [x] HeaderedSelectingItemsControl (We won't support IDataTemplate for now. So no need to wrap those properties)
- [x] SelectingItemsControl
- [x] UniformGrid
- [x] HeaderedItemsControl
- [x] Track Can not be wrapped as it is Xaml-specific and needs a Thumb Template to be rendered 
- [x] Popup
- [x] TabStrip
- [x] Thumb  Can not be wrapped as it is Xaml-specific and needs a Template to be rendered 
- [x] AccessText
- [x] ScrollBar
- [x] TextElement

## Panels
- [x] Canvas
- [x] DockPanel
- [x] Grid
- [x] StackPanel
- [x] WrapPanel

## Shapes
- [x] Shape
- [x] Rectangle
- [x] Ellipse
- [x] Line
- [x] Polyline
- [x] Polygon
- [x] Path
- [x] Sector
- [x] Arc

## Media
- [x] DashStyle
- [x] Pen
- [x] TextDecoration
- [x] Drawing
- [x] GeometryDrawing
- [x] GlyphRunDrawing
- [x] DrawingGroup
- [x] ImageDrawing
- [x] DrawingImage
- [x] CroppedBitmap

## Brush
- [x] Brush
- [x] SolidColorBrush
- [x] TileBrush
- [x]  ImageBrush
- [x] GradientBrush
- [x] ConicGradientBrush
- [x] LinearGradientBrush
- [x] RadialGradientBrush
- [x] VisualBrush

## Geometries
- [x] Geometry
- [x] LineGeometry
- [x] EllipseGeometry
- [x] RectangleGeometry
- [x] PolylineGeometry
- [x] PathGeometry
- [x] CombinedGeometry
- [x] GeometryGroup

## Transforms
- [x] Transform
- [x] MatrixTransform
- [x] SkewTransform
- [x] RotateTransform
- [x] TranslateTransform
- [x] ScaleTransform
- [x] TransformGroup

## PathSegments
- [x] PathSegment
- [x] ArcSegment
- [x] BezierSegment
- [x] LineSegment
- [x] PolylineSegment
- [x] QuadraticBezierSegment
- [x] PathFigure

## Documents
- [x] Run
- [x] Span
- [x] Bold
- [x] LineBreak
- [x] Italic
- [x] Underline

## Avalonia.Controls

- [x] AutoCompleteBox
- [x]  Border
- [x] Button
- [x] ButtonSpinner
- [x] Calendar
- [x] CalendarDatePicker	
- [x] Canvas
- [x] Carousel
- [x] CheckBox
- [x] ComboBox
- [x] ComboBoxItem
- [x] ContextMenu
- [x] DataGrid is part of a separate package
- [x] DataGridCell is part of the separate package
- [x] DatePicker
- [x] DatePickerPresenter
- [x] Decorator
- [x] DropDownButton	
- [x] Expander	
- [x] ExperimentalAcrylicBorder
- [x] ExperimentalAcrylicMaterial
- [x] Flyout		
- [x] GridSplitter
- [x] IconElement	
- [x] Image
- [x] ItemsControl
- [x] ItemsRepeater ? in preview 5 this has been moved to a separate nugget package
- [x] LayoutTransformControl
- [x] ListBox
- [x] ListBoxItem
- [x] Menu
- [x] MenuBase
- [x] MenuFlyout		
- [x] MenuItem
- [x] NativeMenu	
- [x] NativeMenuBar	
- [x] NativeMenuItem	
- [x] NativeMenuItemBase	
- [x] NumericUpDown
- [x] PathIcon	
- [x] ProgressBar
- [x] RadioButton	
- [x] RecyclePool in preview 5 has been moved to a separate package 
- [x] RelativePanel	Can not be wrapped easily as it depends on xaml name references
- [x] RepeatButton		
- [x] ReversibleStackPanel
- [x] ScrollViewer
- [x] Separator
- [x] Slider
- [x] Spinner
- [x] SplitView
- [x] TabControl
- [x] TabItem
- [x] TextBlock
- [x] TextBox	
- [x] TickBar
- [x] TimePicker
- [x] TimePickerPresenter
- [x]  ToggleSwitch
- [x] ToggleButton
- [x] ToggleSplitButton
- [x] SplitButton
- [x] ToolTip
- [x] TopLevel
- [x] #120
- [ ] TreeViewItem
- [x] UserControl
- [x] Viewbox
- [x] VirtualizingStackPanel
- [x] Window
- [x] WindowBase
- [x] WindowIcon
- [x] MaskedTextBox
- [x] SelectableTextBlock
- [x] TrayIcon
- [x] DragDrop ?
- [x] PseudoClasses
- [x] DrawingPresenter
- [x] Application
- [x] RefreshContainer
- [x] RefreshVisualizer
- [x] ThemeAware
- [x] ThemeVariantScope
- [x] TransitioningContentControl

**Comment by ConradRoesch** [comment]
Thanks for putting together this list. I’ve started on the TimePicker and Spinner controls, but let me know if there are others you would like me to prioritize.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edgarfgp** [comment]
> Thanks for putting together this list. I’ve started on the TimePicker and Spinner controls, but let me know if there are others you would like me to prioritize.

Pickers and spinners are a good place to start :).  Let me know if there is anything I can help with. We have a discord channel if you prefer. Thanks again for all your help

**Comment by edgarfgp** [comment]
AvaloniaUIpreview 5 is out . So we need to check the changes to update this list
